### ISSUE TITLE
Peer review week 1

### ISSUE THREAD

**Issue by RowinRuizendaal** [johancvb/web-app-from-scratch-2021#1]
##### Is there a repo description at the top?

Yes there is a repo description

##### Is the repo open to issues?

Yes, as I am making an issue right now :)

##### Does it include a gitignore

Yes it does include a gitignore file

##### Is the concept described well in the readme?

Yes, the concept is described well although it is written in Dutch and the rest of the Readme is written in English, maybe you could be consistent with picking a language :)

##### Is the API described in the readme?

Yes the API is described in the readme

##### Try to understand the code flow

```js
let id_nr = 1
    for(i = 0; i < 50; i++) {
        fetch(`https://free-nba.p.rapidapi.com/players/${id_nr}/?page=0&per_page=30`, {
                id_nr++ 
````
        
 You don't have to use a new let for this you could just use the I from the for loop
 
 ```js
    for(i = 0; i < 50; i++) {
        fetch(`https://free-nba.p.rapidapi.com/players/${i}/?page=0&per_page=30`, {
 
 ```` 
 
 Also with this piece of code, you are pining the API around 50 times which can cause to rate limit, the best way to do this is to fetch first some players and with that received data to loop it through see an example here:
 
 [example](https://github.com/RowinRuizendaal/web-app-from-scratch-2021/blob/master/js/app.js#L27-L33)
 
 Also maybe you should look into some HTML elements such as the main element ;)
 
 [main](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main)
 
##### Check the code against our course's best practices

yes (see above)

##### Check the code for consistency, is code being written the same way in different places?

JS declarations on top are consistent, maybe you can use sections instead of using a div element right away ༼ つ ◕_◕ ༽つ

[section](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section)

##### Does the code follow naming conventions? Do variable and function names make sense to you?

Yes if you are wondering if there is any guide for this, you can check out [BEM](http://getbem.com/naming/)

**Comment by johancvb** [comment]
Thanks! Ik zat inderdaad te kloten met die API rate limit, dus ben blij met je tip :)
