### ISSUE TITLE
Code peer feedback 1

### ISSUE THREAD

**Issue by HappyPantss** [johancvb/web-app-from-scratch-2021#3]
Code
Hey Johan, bij deze mijn peer review op jouw code voor de WAFS API opdracht.

Zie de vinkjes (✔️) en kruisjes (❌) niet als fout of goed, maar een vinkje is voor als je heta af hebt, en een kruisje voor als er nog iets mist :).

✔️ Try to understand the code flow
Lekker bezig man! Je hebt een duidelijke functie gemaakt, met een for loop die door alle spelers gaat. Ook fijn dat je de html element alvast in variables zet, om deze meerdere keren te kunnen gebruiken, top! En voor nu is dit nog niet erg, maar gevoelige informatie zoals de api key, die je nu in app.js hebt staan, kan je beter in een apart bestandje zetten, en dit bestandje aanroepen en in .gitignore zetten, maar daar komen we later op terug met de les als het goed is!

✔️❌ Check the code against our course's best practices
Ik zie geen herhalende code, wat erg goed is, keep this up! Alleen wat de best practices willen is dat je je <script> tag voor je </body> tag zet, en die heb je nu nog na de tag. Maar de rest ziet er goed uit.

✔️ Check the code for consistency, is code being written the same way in different places?
Voor de hoeveelheid code die je nu hebt, zit er zeker consistentie in!

✔️ Does the code follow naming convention? Do variable and function names make sense to you?
De namen van je variables en de functie zijn wat mij betreft erg duidelijk, ik weet iniedergeval wat het doet.

Keep coding~~

**Comment by johancvb** [comment]
Thanks man! 
Ik zal aan de hand van je feedback mijn app verbeteren.
Ik waardeer je input :)

--Johan
